# This is the default configuration file. Enabling and disabling is configured
# in separate files. This file adds all other parameters apart from Enabled.

#inherit_from:
#  - enabled.yml
#  - disabled.yml

# Common configuration.
AllCops:
  # Include common Ruby source files.
  Include:
    - '**/*.gemspec'
    - '**/*.podspec'
    - '**/*.jbuilder'
    - '**/*.rake'
    - '**/*.opal'
    - '**/config.ru'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Capfile'
    - '**/Guardfile'
    - '**/Podfile'
    - '**/Thorfile'
    - '**/Vagrantfile'
    - '**/Berksfile'
    - '**/Cheffile'
    - '**/Vagabondfile'
    - '**/Fastfile'
    - '**/*Fastfile'
  Exclude:
    - 'vendor/**/*'
    - 'packaging/vendor/**/*'
    - 'bin/**/*'  # Exclude bin directory as these are usually generated files
  NewCops: enable

# Metrics configurations
Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'Rakefile'

Metrics/AbcSize:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

# Layout configurations
Layout/LineLength:
  Max: 120

Layout/BlockAlignment:
  Enabled: true

Layout/EndAlignment:
  Enabled: true

Layout/DefEndAlignment:
  Enabled: true

Layout/HashAlignment:
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key
  EnforcedLastArgumentHashStyle: always_inspect

Layout/ParameterAlignment:
  EnforcedStyle: with_first_parameter

Layout/FirstArrayElementIndentation:
  Enabled: true

Layout/AssignmentIndentation:
  Enabled: true

Layout/FirstHashElementIndentation:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: true

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/MultilineOperationIndentation:
  EnforcedStyle: aligned

# Style configurations
Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/Alias:
  EnforcedStyle: prefer_alias

Style/AndOr:
  EnforcedStyle: always

Style/BarePercentLiterals:
  EnforcedStyle: bare_percent

Style/BlockDelimiters:
  EnforcedStyle: line_count_based

Style/Documentation:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/LineEndConcatenation:
  Enabled: false

# Naming configurations
Naming/PredicateName:
  ForbiddenPrefixes:
    - is_
  AllowedMethods:
    - is_a?

Style/TrivialAccessors:
  AllowedMethods:
    - to_s
    - to_hash

# Bundler configurations
Bundler/OrderedGems:
  Enabled: true

# Add required gems for additional functionality
require:
  - rubocop-performance