#!/bin/bash

if ! [ -z "$1" ] && ! [! [ ${1:0:1} == "-" ]; then
  tool=`dirname $0`/src/`basename $1`.rb
else
  tool=
fi

if ! [ -f "$tool" ] || [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
  echo "Usage: patchkit-tools [tool_name] [tool_arguments]"
  echo ""
  echo "Available tools:"
  find `dirname $0`/src/*.rb | xargs -n 1 --replace basename {} ".rb" | xargs -n 1 --replace echo "    {}"
  exit 1
else
  ruby $tool $@
  exit $?
fi


